FROM google/nodejs
MAINTAINER Viktor Farcic "viktor@farcic.com"

# PhantomJS
RUN apt-get update
RUN apt-get install -y build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev

WORKDIR /app

ADD package.json /app/
ADD bower.json /app/
RUN npm install -g grunt-cli
RUN npm install -g gulp
RUN npm install -g bower
RUN npm install -g json-server
RUN npm install
RUN bower install --allow-root --config.interactive=false

ADD run_tests.sh /app/
ADD Gruntfile.js /app/
ADD gulpfile.js /app/
ADD web.js /app/
ADD index.html /app/
ADD api /app/api
ADD src /app/src

CMD ["/app/run_tests.sh"]

# BUILD
# docker build -t vfarcic/books-fe-tests .

# UNIT TESTS
# docker run -t --rm vfarcic/books-fe-tests

# FUNCTIONAL TESTS
# docker run -t --rm \
#   -v /home/vifarcic/IdeaProjects/books-fe/stories:/opt/bdd/data/stories \
#   vfarcic/bdd-runner-phantomjs \
#   -P url=http://172.17.42.1:8080 \
#   -P widthHeight=1024,768 \
#   --story_path data/stories/functional/**

# INTEGRATION TESTS
# docker run -t --rm \
#   -v /home/vifarcic/IdeaProjects/books-fe/stories:/opt/bdd/data/stories \
#   vfarcic/bdd-runner-phantomjs \
#   -P url=http://172.17.42.1:8080 \
#   -P widthHeight=1024,768 \
#   --story_path data/stories/integration/**